import Head from "next/head";

const CompaniesPage = () => {
  return (
    <>
      <Head>
        <title>Baku Electronics Campaigns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Campaigns</h1>
    </>
  );
};

export default CompaniesPage;
