import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import slider1 from "../public/images/slider1.jpeg"
import slider2 from "../public/images/slider2.jpeg"
import slider3 from "../public/images/slider3.jpeg"
import slider4 from "../public/images/slider4.jpeg"
import slider5 from "../public/images/slider5.jpeg"
import slider6 from "../public/images/slider6.jpeg"
import slider7 from "../public/images/slider7.jpeg"
import slider8 from "../public/images/slider8.jpeg"
import slider9 from "../public/images/slider9.jpeg"
import slider10 from "../public/images/slider10.jpeg"
import slider11 from "../public/images/slider11.jpeg"
import slider12 from "../public/images/slider12.jpeg"
import slider13 from "../public/images/slider13.jpeg"

// icons
import { MdOutlineArrowForwardIos } from "react-icons/md";
import { HiOutlineArrowRight } from "react-icons/hi";
import ProductCard from "../components/productCard/ProductCard";
import dataJson from "../data/data.json";
import React, { useState, useEffect, Component } from "react";
import { Swiper, SwiperSlide } from "swiper/react";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Autoplay, Pagination, Navigation } from "swiper";
import Viewed from "../components/viewed/Viewed";

export default function Home() {
  const [data, setData] = useState();

  useEffect(() => {
    setData(dataJson);
  }, []);

  return (
    <>
      <main>
        <Head>
          <title>Baku Electronics Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* section aside-swiper */}
        <section className="aside-swiper" >
          <aside>
            <div className="aside">
              <ul className="content-childe">
                <li className="childe-one">
                  <Link href="/catalog/telefonlar-qadcetler">
                    Telefonlar, planşetlər və qadcetlər
                  </Link>

                  <span className="span">
                    <MdOutlineArrowForwardIos />
                  </span>
                  <div></div>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/catalog/telefonlar-qadcetler/smartphones">Smartfonlar, mobil telefonlar</Link>
                    </li>
                    <li>
                      <Link href="/">Planşetlər</Link>
                    </li>
                    <li>
                      <Link href="/">Smart saatlar və fitnes qolbaqları</Link>
                    </li>

                    <li>
                      <Link href="/">Qulaqlıqlar</Link>
                    </li>
                    <li>
                      <Link href="/">Ev və ofis telefonları</Link>
                    </li>
                    <li>
                      <Link href="/">Qol saatları</Link>
                    </li>
                    <li>
                      <Link href="/">Xarici akkumulyatorlar, Power Bank</Link>
                    </li>
                    <li>
                      <Link href="/">Aksesuarlar</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-two">
                  <Link href="/">Televizorlar, audio-video və foto</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Televizorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Ev kinoteatrları və saundbarlar</Link>
                    </li>
                    <li>
                      <Link href="/">Musiqi mərkəzləri</Link>
                    </li>

                    <li>
                      <Link href="/">
                        Portativ dinamiklər və akustik sistemlər
                      </Link>
                    </li>
                    <li>
                      <Link href="/">TV bokslar</Link>
                    </li>
                    <li>
                      <Link href="/">Proyektorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Ekşn kameralar</Link>
                    </li>
                    <li>
                      <Link href="/">Fotoaparatlar</Link>
                    </li>
                    <li>
                      <Link href="/">Aksesuarlar</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-three">
                  <Link href="/">Notbuklar və kompüter texnikası</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Notbuklar</Link>
                    </li>
                    <li>
                      <Link href="/">Predator Thronos kompüterləri</Link>
                    </li>
                    <li>
                      <Link href="/">Masaüstü kompüterlər</Link>
                    </li>

                    <li>
                      <Link href="/">Monobloklar</Link>
                    </li>
                    <li>
                      <Link href="/">Monitorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Printerlər və kartriclər</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Klaviatura və kompüter siçanları</Link>
                    </li>
                    <li>
                      <Link href="/">Şəbəkə avadanlığı</Link>
                    </li>
                    <li>
                      <Link href="/">Xarici toplayıcı disklər HDD və SSD</Link>
                    </li>
                    <li>
                      <Link href="/">Aksesuarlar</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-four">
                  <Link href="/">Kondisionerlər və digər iqlim texnikası</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Kombi</Link>
                    </li>
                    <li>
                      <Link href="/">Kondisionerlər</Link>
                    </li>
                    <li>
                      <Link href="/">Su qızdırıcıları, qazanlar, kolonkalar</Link>
                    </li>

                    <li>
                      <Link href="/">Kombi radiatorları</Link>
                    </li>
                    <li>
                      <Link href="/">Konvektorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Mikroiqlim</Link>
                    </li>
                    <li>
                      <Link href="/">Ventilyatorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Aksesuarlar</Link>
                    </li>
                    <li>
                      <Link href="/">
                        Mərkəzləşdirilmiş isitmə, soyutma və havalandırma
                        sistemləri
                      </Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-five">
                  <Link href="/">Böyük məişət texnikası</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Soyuducular</Link>
                    </li>
                    <li>
                      <Link href="/">Dondurucu kameralar</Link>
                    </li>
                    <li>
                      <Link href="/">Paltaryuyan maşınlar</Link>
                    </li>

                    <li>
                      <Link href="/">Quruducu maşınlar</Link>
                    </li>
                    <li>
                      <Link href="/">Qabyuyan maşınlar</Link>
                    </li>
                    <li>
                      <Link href="/">Aspiratorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Bişirmə panelləri</Link>
                    </li>
                    <li>
                      <Link href="/">Quraşdırılan sobalar</Link>
                    </li>
                    <li>
                      <Link href="/">Mətbəx plitələri</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-six">
                  <Link href="/">Kiçik məişət texnikası</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Mətbəx köməkçiləri</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Yemək hazırlanması</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Qəhvə, şirə, içkilər</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>

                    <li>
                      <Link href="/">Evə və geyimə qulluq</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Aksesuarlar</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-seven">
                  <Link href="/">Gözəllik və sağlamlıq</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Fenlər</Link>
                    </li>
                    <li>
                      <Link href="/">Saç üçün düzləşdiricilər</Link>
                    </li>
                    <li>
                      <Link href="/">Elektromaşa</Link>
                    </li>

                    <li>
                      <Link href="/">Multistayler</Link>
                    </li>
                    <li>
                      <Link href="/">Elektrik üzqırxan</Link>
                    </li>
                    <li>
                      <Link href="/">Saç qırxan</Link>
                    </li>
                    <li>
                      <Link href="/">Trimmerlər</Link>
                    </li>
                    <li>
                      <Link href="/">Epilyatorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Döşəmə tərəziləri</Link>
                    </li>
                    <li>
                      <Link href="/">Elektrik diş fırçaları, irriqatorlar</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-eight">
                  <Link href="/">Oyun konsolları və aksessuarlar</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Oyun konsolları</Link>
                    </li>
                    <li>
                      <Link href="/">Video oyunlar</Link>
                    </li>
                    <li>
                      <Link href="/">Oyun konsolları üçün aksessuarlar</Link>
                    </li>

                    <li>
                      <Link href="/">Oyun kresloları</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-nine">
                  <Link href="/">Mebel, tekstil və dekor</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Qonaq otağı</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>

                    <li>
                      <Link href="/">Yataq otağı</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Yumşaq mebel</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>

                    <li>
                      <Link href="/">Gənc otağı</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">TV stendlər</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Jurnal masaları</Link>
                    </li>
                    <li>
                      <Link href="/">Döşəklər</Link>
                    </li>
                    <li>
                      <Link href="/">Ev tekstili</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Dekor və interyer</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-ten">
                  <Link href="/">Qab-qacaq, tava-qazan</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Qab-qacaq</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Tava-Qazan</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-elevn">
                  <Link href="/">Ev və bağ</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Manqallar və aksessuarlar</Link>
                    </li>
                    <li>
                      <Link href="/">İşıqlandırılma</Link>
                    </li>
                    <li>
                      <Link href="/">Ağıllı ev</Link>
                    </li>

                    <li>
                      <Link href="/">Seyflər</Link>
                    </li>
                    <li>
                      <Link href="/">İnşaat məhsulları</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-twelve">
                  <Link href="/">İdman və fəal istirahət</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Motosiklet</Link>
                    </li>
                    <li>
                      <Link href="/">Benzinli skuter</Link>
                    </li>
                    <li>
                      <Link href="/">Elektroskuter</Link>
                    </li>

                    <li>
                      <Link href="/">Velosipedlər</Link>
                    </li>
                    <li>
                      <Link href="/">Samokatlar</Link>
                    </li>
                    <li>
                      <Link href="/">Elektrosamokatlar</Link>
                    </li>
                    <li>
                      <Link href="/">Skeytbordlar</Link>
                    </li>

                    <li>
                      <Link href="/">Qiroskuterlər və siqveylər</Link>
                    </li>
                    <li>
                      <Link href="/">Skuter və motosiklet aksesuarları</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                    <li>
                      <Link href="/">Velosiped aksesuarları</Link>
                    </li>
                    <li>
                      <Link href="/">Turizm və kempinq</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
                <li className="childe-thirteen">
                  <Link href="/">Uşaq aləmi</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">LEGO konstruktorlar</Link>
                    </li>
                    <li>
                      <Link href="/">Oyuncaqlar</Link>
                    </li>
                  </ul>
                </li>
                <li className="childe-fourteen">
                  <Link href="/">Musiqi alətləri və avadanlıqları</Link>
                  <span>
                    <MdOutlineArrowForwardIos />
                  </span>
                  <ul className="dropdawn">
                    <li>
                      <Link href="/">Gitaralar</Link>
                    </li>
                    <li>
                      <Link href="/">Nəfəsli alətlər</Link>
                    </li>
                    <li>
                      <Link href="/">Musiqi avadanlığı</Link>
                      <span>
                        <MdOutlineArrowForwardIos />
                      </span>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </aside>

          <div className="swiper">
            <Swiper
              spaceBetween={30}
              centeredSlides={true}
              autoplay={{
                delay: 2500,
                disableOnInteraction: false,
              }}
              pagination={{
                clickable: true,
              }}
              navigation={true}
              modules={[Autoplay, Pagination, Navigation]}
              className="mySwiper"
            >
              <SwiperSlide>
                <Image
                  src={slider1}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider2}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider3}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider4}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider5}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider6}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider7}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider8}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider9}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider10}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider11}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider12}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
              <SwiperSlide>
                <Image
                  src={slider13}
                  alt="slide"
                  width={1003}
                  height={471}
                />
              </SwiperSlide>
            </Swiper>
          </div>
          {/* section Smartphones */}
        </section>
        <Viewed />
        <section className="smartphones">
          <div className="container">
            <div className="title">
              <h2>Smartfonlar</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["telefonlar-qadcetler"]?.smartphones?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* section Watches */}
        <section className="watches">
          <div className="container">
            <div className="title">
              <h2>Smart saatlar və fitnes qolbaqları</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["telefonlar-qadcetler"]?.watches?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* section Notebook */}
        <section className="notebook">
          <div className="container">
            <div className="title">
              <h2>Noutbuklar</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["noutbuklar-kompyuterler"]?.notebooks?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>
        {/* section Refrigerators */}
        <section className="refrigerators">
          <div className="container">
            <div className="title">
              <h2>Soyuducular</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["boyuk-meiset-texnikasi"]?.refrigerators?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>
        {/* section tv */}
        <section className="tv">
          <div className="container">
            <div className="title">
              <h2>Televizorlar</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["tv-audio-video"]?.tv?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>
        {/* section Washing machines */}
        <section className="washing-machines">
          <div className="container">
            <div className="title">
              <h2>Paltaryuyan maşınlar</h2>
            </div>
            <div className="list-holder">
              <ul>
                {data?.products?.["boyuk-meiset-texnikasi"]?.washingMachine?.items?.slice(0, 4).map((product) => (
                  <ProductCard key={product?.id} item={product} />
                ))}
              </ul>
            </div>
          </div>
        </section>
      </main >
    </>

  );
}

